title: "Projet HELIOS - Mercredi Cyber"
description: "Site dédié aux conférences Mercredi Cyber du Projet HELIOS"
baseurl: ""
url: "https://heliosc4i.github.io/cyberwednesday/"
theme: minima
plugins:
  - jekyll-paginate
paginate: 5
paginate_path: "/page:num/"
